### ISSUE TITLE
About Radio Mods on Sofia platform

### ISSUE THREAD

**Issue by Doume** [hvdwolf/JoyingBinRepo#1]
I've tried to install radio mods on my head unit based on Intel Sofia3GR platform
But apk install seems to be rejected for 'incompatibility'....
Checking the manifest in your apk (BW-RDS mod) , it seems the platform name is set to "px5", and not "sofia" like in original .apk
Is that could be the reason of reject ?

Thanks a lot for your work

**Comment by hvdwolf** [comment]
Which mod did you try? The BW-RDS for 8, or the BW-RDS for 6?

There is a set for Android 6 for Sofia, which do work.
The version for Android 8 should work, but might give difficulties.

Harry

Op ma 1 apr. 2019 om 18:26 schreef Dominique DAMBRAIN <
notifications@github.com>:

**Comment by Doume** [comment]
Thanks for answer

I'm sure to have downloaded version for 6.0.1
https://github.com/hvdwolf/JoyingBinRepo/tree/master/Radio-Mod/6.0.1/BW-RDS
Inside this apk, the AndroidManifest.xml contains this :

<application android:allowBackup="true" android:icon="@drawable/radio_icon" android:label="@string/app_name" android:name="com.syu.app.AppRadio" android:theme="@android:style/Theme.NoTitleBar">
        <meta-data android:name="platform" android:value="px5"/>
        <meta-data android:name="client" android:value="JY"/>
        <meta-data android:name="ui_id" android:value="1"/>
        <meta-data android:name="compile" android:value="2017-11-09 18:01:53/JY-1-C9-Radio-V1.0"/>

And it cannot be installed on my head unit...

**Comment by hvdwolf** [comment]
How did you try to install it? You cannot simply double-click this to make it install as it is a system app. You need to directly place it in /system/app/JY-... via ADB, or use my JET apk to do that.

The PX5 in the AndroidManifest is not relevant. The Sofia apks contained even weirder references, simply because FYT doesn't do proper housekeeping.

**Comment by Doume** [comment]
Of course, I used your script "radiomod.sh" to install it into /system/app
- remove dalvik cache for radio
- put your package in /system/app
- reboot head unit
But no success....
You'll find attached the log file for my next attempt : No success : After reboot, no popup window to notify "updating Android apps", and still standard radio application running....
[JET-20190402.log](https://github.com/hvdwolf/JoyingBinRepo/files/3034614/JET-20190402.log)
